name: Text Categorizer Tests
run-name: ${{ github.actor }} is running tests 🧪
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Report status
        if: always()
        run: |
          echo "✅ Test status: ${{ job.status }}"
          echo "📝 Branch: ${{ github.ref }}"
          echo "📦 Repository: ${{ github.repository }}"
